# Node to get data from. Can be localhost.
nodeAddress: https://nodes.wavesnodes.com

# How many blocks to fetch on single download request.
# Consider lowering this setting if fetching takes too long.
# Possible values: 1 to 100.
blocksPerRequest: 100

# How many blocks to fetch on single update request.
# More blocks — deeper rollback safety, but longer updates (less realtime results).
# Possible values: 1 to 100, recommended: 1 to 10.
blocksPerUpdate: 5

# Minimal interval between initiating updates, milliseconds ('throttle' value)
# Frequent updates mean data is more up-to-date, but load database more
updateThrottleInterval: 500

# PostgreSQL credentials.
# Tables must be created beforehand according to SQL files.
postgresHost: # IP, hostname or localhost
postgresPort: #5 432 or other
postgresDatabase: # database name
postgresUser: # username
postgresPassword: # password